Repository smartxworks/sunmao-ui, pull requests merged in 2022-05, with the labels that each got.

#392 fix some bugs
  packages/arco-lib/src/components/Tree.tsx
  packages/arco-lib/src/examples/ExampleIndexPage.tsx
  packages/arco-lib/src/examples/pages/dropdown/basicUsage.ts
  packages/arco-lib/src/examples/pages/dropdown/index.tsx
  packages/arco-lib/src/examples/pages/dropdown/withAvatar.ts
  packages/editor/src/components/DataSource/ApiForm/Params.tsx
  packages/editor/src/services/EditorStore.ts
Labels: Conflict

#412 refactor editor mask
  packages/editor/__tests__/editorMask.spec.ts
  packages/editor/src/components/Editor.tsx
  packages/editor/src/components/EditorMaskWrapper/EditorMask.tsx
  packages/editor/src/components/EditorMaskWrapper/EditorMaskManager.ts
  packages/editor/src/components/EditorMaskWrapper/EditorMaskWrapper.tsx
  packages/editor/src/components/EditorMaskWrapper/index.ts
  packages/editor/src/services/eventBus.ts
Labels: bug, editor, refactor

#423 Use elementFromPoint api to refactor
  packages/editor/__tests__/editorMask.spec.ts
  packages/editor/src/components/EditorMaskWrapper/EditorMask.tsx
  packages/editor/src/components/EditorMaskWrapper/EditorMaskManager.ts
  packages/editor/src/components/EditorMaskWrapper/EditorMaskWrapper.tsx
  packages/editor/src/services/eventBus.ts
Labels: refactor

#422 feat(utilMethod): add spec to utilMethod
  packages/chakra-ui-lib/src/components/Types/Toast.ts
  packages/core/src/index.ts
  packages/core/src/utilMethod.ts
  packages/editor-sdk/src/components/Widgets/EventWidget.tsx
  packages/runtime/src/services/Registry.tsx
  packages/runtime/src/services/UtilMethodManager.ts
  packages/runtime/src/types/utilMethod.ts
  packages/runtime/src/utilMethods/ScrollIntoComponent.ts
  packages/runtime/src/utils/buildKit.ts
Labels: breaking change
